services:
    nulldev_skeleton.paths:
        class: NullDev\SkeletonBundle\Paths
        arguments: ["%nulldev_skeleton.config%"]



    null_dev.skeleton.source_factory.broadway.elastic_search.read.entity:
        class: NullDev\Skeleton\Broadway\SourceFactory\Read\ElasticSearch\ReadEntitySourceFactory
        arguments:
          - "@null_dev.skeleton.source.class_source_factory"
          - "@null_dev.skeleton.definition.php.definition_factory"

    null_dev.skeleton.source_factory.broadway.elastic_search.read.projector:
        class: NullDev\Skeleton\Broadway\SourceFactory\Read\ElasticSearch\ReadProjectorSourceFactory
        arguments:
          - "@null_dev.skeleton.source.class_source_factory"
          - "@null_dev.skeleton.definition.php.definition_factory"

    null_dev.skeleton.source_factory.broadway.elastic_search.read.repository:
        class: NullDev\Skeleton\Broadway\SourceFactory\Read\ElasticSearch\ReadRepositorySourceFactory
        arguments:
          - "@null_dev.skeleton.source.class_source_factory"
          - "@null_dev.skeleton.definition.php.definition_factory"



    null_dev.skeleton.source_factory.broadway.command:
        class: NullDev\Skeleton\Broadway\SourceFactory\CommandSourceFactory
        arguments:
          - "@null_dev.skeleton.source.class_source_factory"
          - "@null_dev.skeleton.definition.php.definition_factory"

    null_dev.skeleton.source_factory.broadway.event:
        class: NullDev\Skeleton\Broadway\SourceFactory\EventSourceFactory
        arguments:
          - "@null_dev.skeleton.source.class_source_factory"
          - "@null_dev.skeleton.definition.php.definition_factory"


    null_dev.skeleton.source_factory.broadway.event_sourced_aggregate_root:
        class: NullDev\Skeleton\Broadway\SourceFactory\EventSourcedAggregateRootSourceFactory
        arguments:
          - "@null_dev.skeleton.source.class_source_factory"
          - "@null_dev.skeleton.definition.php.definition_factory"

    null_dev.skeleton.source_factory.broadway.event_sourcing_repository:
        class: NullDev\Skeleton\Broadway\SourceFactory\EventSourcingRepositorySourceFactory
        arguments:
          - "@null_dev.skeleton.source.class_source_factory"
          - "@null_dev.skeleton.definition.php.definition_factory"

    null_dev.skeleton.source_factory.uuid_identity:
        class: NullDev\Skeleton\SourceFactory\UuidIdentitySourceFactory
        arguments:
          - "@null_dev.skeleton.source.class_source_factory"
          - "@null_dev.skeleton.definition.php.definition_factory"


    null_dev.skeleton.source.class_source_factory:
        class: NullDev\Skeleton\Source\ClassSourceFactory

    null_dev.skeleton.definition.php.definition_factory:
        class: NullDev\Skeleton\Definition\PHP\DefinitionFactory

    null_dev.skeleton.path.reader.source_code:
        class: NullDev\Skeleton\Path\Readers\SourceCodePathReader


